import Config
config :astra,
  host: System.get_env("CASS_HOST"),
  username: System.get_env("CASS_USERNAME"),
  password: System.get_env("CASS_PASSWORD")

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :lunch, LunchWeb.Endpoint,
  url: [host: System.get_env("HOST") || "localhost", port: 80],
  http: [
    port: String.to_integer(System.get_env("PORT") || "4000"),
    transport_options: [socket_opts: [:inet6]]
  ]
