apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunch-app
  name: lunch-app-service
  namespace: frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: lunch-app
  sessionAffinity: None
  type: LoadBalancer
